import React from 'react';
import {useCurrentFrame, useVideoConfig, Sequence, interpolate, Easing} from 'remotion';
import {Biome} from './lib/biomes';
import {Plane, CameraMoves, composeCams, Camera} from './lib/stage3d';
import {GradeLayer} from './lib/lighting';
import {Element, Placed} from './lib/registry';
import {MaterialDefs} from './lib/materials';
import type {RegionName} from './lib/lighting';
import {FONT} from './lib/type';

// =============================================================================
// THE DISPATCH — the composition the routine actually renders.
//
// IT DID NOT EXIST. `prompts/dispatch_routine.md` Phase 5 has always run
//
//     npx remotion render Dispatch out/dispatch/film.mp4 --props=...
//
// and `Root.tsx` registered Proof, the review sheets and ten region sheets and
// nothing named Dispatch. Remotion exits with "No composition with the ID
// 'Dispatch' found", so **every unattended run produced no film**, and the two
// gates that would have caught it were being invoked with no arguments and
// exiting 2 before they read anything. Three faults stacked into one silence.
//
// So this is the deliverable, and its shape follows the routine's own rule:
// SCENES ARE CODE, STORY IS DATA. The board arrives through `--props`, names a
// region, a camera move, a plane stack and what stands on each plane, and this
// turns it into a film. `lib/registry.tsx` is the boundary where a name becomes a
// component, and it THROWS on a name it does not have rather than rendering an
// empty plane, because a scene that draws nothing renders without error.
//
// WHAT THIS IS NOT. It is not a template that makes every Dispatch look alike.
// The composition axes and the cross-run divergence rule in `storyboard_check`
// govern that, and they operate on the board this reads. A run that wants a shot
// this cannot express writes a bespoke scene component and registers it; the
// engine is a floor, not a ceiling.
// =============================================================================

export interface Scene {
  id: string;
  start_s: number;
  duration_s: number;
  region: RegionName;
  county: string;
  camera_strategy: keyof typeof CameraMoves;
  /** Ordered far to near. Each plane's z, the director's name for it, and what
   *  stands on it.
   *
   *  `label` is not decoration and it is not read here. THE BOARD IS THE PROPS: this
   *  same file is what `storyboard_check` gates at Gate 0, and the label is what a
   *  director boards and what the divergence signature reads. Two shots whose plane
   *  stacks are named and populated the same way are the same shot, however
   *  differently the captions read. */
  planes: {z: number; label?: string; items: Placed[]}[];
  /** screen-space, never in the world: see the note on chrome below */
  super?: string;
  caption?: string;
  weather?: 'norther' | 'dust' | 'overcast' | 'night';
  seed?: number;
  groundY?: number;
}

export type DispatchProps = {
  runtime_s: number;
  scenes: Scene[];
  title?: string;
  /** THE CREDITS, and for the music they are not a courtesy.
   *
   *  A bed under a permissive licence is granted in exchange for the attribution, so
   *  this text IS the licence being paid. It is generated by `scripts/music.py` from
   *  the vetted registry, never typed, and `music.py --verify-film` refuses to ship a
   *  film whose credits do not carry the track's title, artist and licence name.
   *  Passing nothing is legitimate and means the film used no music. */
  credits?: string;
  /** How long the end card holds. Long enough to read is the only requirement. */
  credits_s?: number;
  /** the composition fingerprint, carried so the render can be traced to a board */
  fingerprint?: Record<string, string>;
  // Remotion types a Composition's props as Record<string, unknown>, so the shape has
  // to stay assignable to it. The index signature is what makes that true; the named
  // fields above are what the component and the gates actually rely on.
  [k: string]: unknown;
};

/**
 * The default props exist so `npx remotion still Dispatch` works with no board at
 * all, which is what makes this composition testable in CI. They are a real
 * two-scene film rather than a placeholder, because a default that cannot render
 * is a default that hides a break.
 */
export const DEFAULT_DISPATCH: DispatchProps = {
  runtime_s: 10,
  title: 'The newest industry sits on the oldest land',
  scenes: [
    {
      id: 's1', start_s: 0, duration_s: 5, region: 'rolling_plains', county: 'Taylor',
      camera_strategy: 'dollyThrough', seed: 31, groundY: 1060,
      super: 'Taylor County',
      planes: [
        {z: 860, label: 'sky', items: [{kind: 'turkeyVulture', x: 760, y: 330, scale: 0.5, seed: 51}]},
        {z: 640, label: 'ridge', items: [
          {kind: 'pumpjack', x: 120, y: 962, scale: 0.12, seed: 40, props: {rpm: 7, wear: 0.4}},
          {kind: 'pumpjack', x: 620, y: 958, scale: 0.13, seed: 49, props: {rpm: 8, wear: 0.5}},
          {kind: 'windTurbine', x: 980, y: 958, scale: 0.026, seed: 3},
        ]},
        {z: 300, label: 'mid', items: [{kind: 'dataCentre', x: -40, y: 1180, scale: 0.12, seed: 5,
                          props: {wear: 0.25}}]},
        {z: 150, label: 'near', items: [
          {kind: 'person', x: 330, y: 1420, scale: 0.8, props: {cast: 'engineer', pose: 'point'}},
          {kind: 'person', x: 620, y: 1426, scale: 0.8, facing: -1,
           props: {cast: 'rancher', pose: 'hands-hips', emotion: 'wry'}},
        ]},
        {z: 40, label: 'hero', items: [{kind: 'mesquite', x: -60, y: 2020, scale: 0.28, seed: 9}]},
      ],
    },
    {
      id: 's2', start_s: 5, duration_s: 5, region: 'high_plains', county: 'Lubbock',
      camera_strategy: 'craneDown', seed: 12, groundY: 1120,
      super: 'and the water under it',
      planes: [
        {z: 700, label: 'sky', items: [{kind: 'waterTower', x: 820, y: 1000, scale: 0.084, seed: 2}]},
        {z: 420, label: 'ridge', items: [{kind: 'windmill', x: 200, y: 1060, scale: 0.22, seed: 4}]},
        {z: 200, label: 'mid', items: [{kind: 'stockTank', x: 620, y: 1180, scale: 0.17, seed: 6}]},
        {z: 90, label: 'near', items: [{kind: 'jackrabbit', x: 300, y: 1300, scale: 0.9, seed: 24}]},
      ],
    },
  ],
};

const clamp01 = (v: number) => Math.max(0, Math.min(1, v));

/** One scene, staged from data. */
export const DispatchScene: React.FC<{scene: Scene; fps: number}> = ({scene, fps}) => {
  const f = useCurrentFrame();
  const dur = Math.max(1, Math.round(scene.duration_s * fps));
  const p = interpolate(f, [0, dur], [0, 1], {
    extrapolateLeft: 'clamp', extrapolateRight: 'clamp',
    easing: Easing.bezier(0.35, 0, 0.2, 1),
  });

  // The move is named by the board and resolved here. An unknown name would
  // silently give a static camera, which storyboard_check already refuses at
  // Gate 0 and which this refuses again at render time, because the two checks
  // guard different moments and the cheap one is not always the one that runs.
  const move = CameraMoves[scene.camera_strategy];
  if (!move) {
    throw new Error(
      `scene ${scene.id}: camera_strategy "${scene.camera_strategy}" is not a composed move. ` +
      `A static camera wastes the engine, so this stops rather than rendering one. ` +
      `Known: ${Object.keys(CameraMoves).join(', ')}`);
  }
  const camera: Camera = composeCams(move(p));

  return (
    <div style={{position: 'absolute', inset: 0, background: '#0d1220'}}>
      <Biome region={scene.region} frame={f} camera={camera} seed={scene.seed ?? 1}
        groundY={scene.groundY ?? 1060} weather={scene.weather}>
        {scene.planes.map((pl, i) => (
          <Plane key={i} z={pl.z}>
            {/* OVERFLOW VISIBLE, and it is not a nicety. An <svg> clips to its
                viewport, so with the default a plane could not draw one pixel outside
                0..1080 -- and a plane pushed back by perspective is scaled DOWN about
                the frame centre, so it can no longer reach the edges it was just
                clipped to. The result was a bare strip down both margins of every
                receding plane: a ground treatment sized exactly to the frame arrived
                on screen a hundred pixels narrow. Nothing errored, and the film
                looked like it had a border it was never given. */}
            <svg width={1080} height={1920} viewBox="0 0 1080 1920"
              style={{overflow: 'visible'}}>
              {/* Once per plane <svg>, because a material overlay resolves url(#mat-*)
                  within its own document and each plane is its own svg. Without this
                  every bark, corrugated and granite surface the nostalgia modules
                  paint would fall back to nothing in the finished film. */}
              <MaterialDefs />
              {/* The ADDRESS is threaded in, not just the item. An element the board
                  did not seed takes its variation from where it stands, which is
                  distinct per instance and the same on every frame. See `seedFor`
                  for why appearance may not come from tree position. */}
              {pl.items.map((item, j) => (
                <Element key={`${item.kind}-${j}`} item={item} frame={f}
                  at={{scene: scene.id, plane: i, item: j}} />
              ))}
            </svg>
          </Plane>
        ))}
      </Biome>

      {/* SCREEN-SPACE CHROME STAYS OUTSIDE Stage3D. A super or a caption is not a
          world object, and putting one in the world is how a title ends up lying
          on the ground during a crane move. */}
      <svg width={1080} height={1920} viewBox="0 0 1080 1920"
        style={{position: 'absolute', inset: 0}}>
        <GradeLayer f={f} vignette={0.2} grain={0.045} bloom={0.12} />
        {scene.super && (
          <g opacity={interpolate(f, [4, 18, dur - 12, dur - 2], [0, 1, 1, 0],
            {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})}>
            <text x={64} y={210} fontSize={74} fontWeight={700} fill="#f2ede2"
              fontFamily={FONT.display}>{scene.super}</text>
            <rect x={64} y={244} width={132} height={5} fill="#c8703a" />
          </g>
        )}
        {scene.caption && (
          <g opacity={clamp01(interpolate(f, [2, 12], [0, 1],
            {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'}))}>
            <rect x={54} y={1660} width={972} height={92} rx={6} fill="#0d1220" opacity={0.72} />
            <text x={78} y={1716} fontSize={34} fill="#e4ded2"
              fontFamily={FONT.body}>{scene.caption}</text>
          </g>
        )}
      </svg>
    </div>
  );
};

/** The end card. Plain, dark, legible, and it holds still: a credit that slides or
 *  fades out early is a credit that was not read, and for the music that is the
 *  licence going unpaid. Set in the body serif at caption size, left aligned, because
 *  a centred block of licence text is decoration pretending to be a title. */
export const CreditsCard: React.FC<{text: string}> = ({text}) => {
  const f = useCurrentFrame();
  // SVG TEXT DOES NOT WRAP, and the first render of this card ran the attribution off
  // the right edge mid-URL. That is not a layout nit: the licence URL is part of the
  // attribution, so a credit clipped by the frame is a licence not actually paid on
  // screen, while every string check upstream still passes. GATE_LESSONS: a gate that
  // reads text cannot see text that has not been laid out yet.
  const PER = 52;                       // characters that fit at 27px in 1080 wide
  const wrapped: {s: string; head: boolean}[] = [];
  for (const raw of text.split('\n')) {
    const l = raw.trim();
    if (!l) continue;
    const head = l === l.toUpperCase() && l.length < 24;
    if (head) { wrapped.push({s: l, head}); continue; }
    let cur = '';
    for (const w of l.split(' ')) {
      // a long URL is never broken: it is moved to its own line whole, because a URL
      // split across two lines is not a URL anyone can follow.
      if ((cur + ' ' + w).trim().length > PER && cur) { wrapped.push({s: cur.trim(), head}); cur = w; }
      else cur += ' ' + w;
    }
    if (cur.trim()) wrapped.push({s: cur.trim(), head});
  }
  return (
    <div style={{position: 'absolute', inset: 0, background: '#0d1220'}}>
      <svg width={1080} height={1920} viewBox="0 0 1080 1920">
        <g opacity={interpolate(f, [0, 12], [0, 1],
          {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})}>
          {wrapped.map((l, i) => (
            <text key={i} x={78} y={700 + i * 46} fontSize={l.head ? 30 : 26}
              fill={l.head ? '#c8703a' : '#e4ded2'} fontFamily={FONT.body}
              letterSpacing={l.head ? 3 : 0}>{l.s}</text>
          ))}
        </g>
      </svg>
    </div>
  );
};

export const Dispatch: React.FC<DispatchProps> = ({scenes, credits, credits_s = 4}) => {
  const {fps} = useVideoConfig();
  const end = scenes.reduce((m, s) => Math.max(m, s.start_s + s.duration_s), 0);
  return (
    <>
      {scenes.map((s) => (
        <Sequence key={s.id} from={Math.round(s.start_s * fps)}
          durationInFrames={Math.max(1, Math.round(s.duration_s * fps))}>
          <DispatchScene scene={s} fps={fps} />
        </Sequence>
      ))}
      {credits && credits.trim() && (
        <Sequence from={Math.round(end * fps)}
          durationInFrames={Math.max(1, Math.round(credits_s * fps))}>
          <CreditsCard text={credits} />
        </Sequence>
      )}
    </>
  );
};

/**
 * The film's length comes from the BOARD, never from a constant here.
 *
 * A hardcoded durationInFrames would silently truncate a longer film or pad a
 * shorter one with black, and both are the kind of fault a run reports as
 * success. Remotion calls this with the real props at render time.
 */
export const dispatchMetadata = ({props}: {props: Record<string, unknown>}) => {
  const board = props as unknown as DispatchProps;
  const last = (board.scenes ?? []).reduce(
    (m, s) => Math.max(m, (s.start_s ?? 0) + (s.duration_s ?? 0)), 0);
  // The credits card is APPENDED, so the composition has to grow by its length. Without
  // this the card renders past the end of the film and is simply never seen, which for
  // a permissively licensed bed means the attribution silently went unpaid.
  const tail = (board.credits ?? '').trim() ? (board.credits_s ?? 4) : 0;
  const seconds = Math.max(board.runtime_s ?? 0, last) + tail;
  if (seconds <= 0) {
    throw new Error(
      'Dispatch: the board declares no runtime and no scenes, so there is nothing to render. ' +
      'A zero-length composition renders "successfully" as an empty file.');
  }
  return {durationInFrames: Math.round(seconds * 30)};
};
