#!/usr/bin/env python3
"""composition_check.py — the id the routine renders must be an id the engine registers.

WHY THIS EXISTS

`prompts/dispatch_routine.md` Phase 5 has always run

    npx remotion render Dispatch out/dispatch/film.mp4 --props=...

and `video-engine/src/Root.tsx` registered `Proof`, five review sheets and ten region sheets, and
nothing at all called `Dispatch`. Remotion exits with "No composition with the ID 'Dispatch'
found", so **every unattended run produced no film.**

Nothing caught it. `tsc` is clean because a composition id is a string. `engine_lint` reads colour
literals. `wiring_check` knows about agents and scripts and has no notion of a Remotion
composition. `HANDOFF.md` opened with "Everything in this repo works when run by hand", which was
true of every part and false of the whole.

That is the same shape as GATE_LESSONS 19 one layer out: the deliverable itself was the orphan.

TWO DIRECTIONS.

  GHOST: a prompt renders an id `Root.tsx` does not register. This is the fatal one, and it fails
  at the worst moment, after the research, the board, the scenes and the voice are all done.

  ORPHAN: a composition is registered and no prompt or workflow ever renders it. Review sheets are
  legitimately rendered by hand, so those are listed in BY_HAND with a reason each, the same
  discipline `wiring_check` uses for standalone scripts.

    composition_check.py
    composition_check.py --self-test

Exit 0 clean, 1 a mismatch, 2 the checker could not run.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ROOT_TSX = REPO / "video-engine" / "src" / "Root.tsx"

# Compositions rendered by a person, not by the routine. Each needs a reason, because
# "it is a review surface" is what an orphan says about itself.
BY_HAND = {
    "Proof": "the engine proof scene, rendered when the stack changes",
    "CastSheet": "review surface for the cast rig",
    "FaunaSheet": "review surface for the bestiary",
    "VehicleSheet": "review surface for the fleet",
    "CivicSheet": "review surface for the civic kit",
    # THE APPLICATION SHEETS. Rendered by hand when a module changes, the same as the
    # four above. They are listed one by one rather than covered by a `*Sheet` glob,
    # because a glob would mean the next composition somebody names "Sheet" is exempt
    # by accident, and this file exists to catch exactly that.
    "FarmSheet": "review surface for agriculture",
    "RoadSheet": "review surface for freight",
    "MachineRoomSheet": "review surface for compute",
    "ClinicSheet": "review surface for the clinic",
    "WaterSheet": "review surface for measurement and warning",
    "PlantSheet": "review surface for the plant floor",
    "SensingSheet": "review surface for the overlays",
    # THE NOSTALGIA SHEETS. Rendered by hand when a nostalgia module changes, one per
    # module and one for the field-cover flora, listed one by one for the same reason
    # the application sheets are: a *Sheet glob would exempt the next orphan by name.
    "FloraSheet": "review surface for the specimen flora",
    "FloraFieldSheet": "review surface for the field-cover flora",
    "SkySheet": "review surface for the sky states",
    "RoadsideSheet": "review surface for the drive-by roadside",
    "HometownSheet": "review surface for the school and Friday night kit",
    "HomeplaceSheet": "review surface for the house and yard",
    "TejanoSheet": "review surface for Tejano and border Texas",
    "BlackTexasSheet": "review surface for Black Texas",
}

# Region-* ids are generated by a map in Root.tsx and reviewed as a set.
BY_HAND_PREFIX = ("Region-",)


def registered() -> set[str]:
    """Composition ids Root.tsx actually registers, literals and template forms alike."""
    src = ROOT_TSX.read_text(encoding="utf-8")
    ids = set(re.findall(r'<Composition[^>]*?\bid=["\']([A-Za-z0-9_-]+)["\']', src, re.S))
    # The generated set: id={`Region-${...}`} mapped over a REGIONS list.
    #
    # The array is found with a regex rather than by splitting on "]", because the
    # declaration reads `const REGIONS: RegionName[] = [...]` and the TYPE contains a
    # bracket. Splitting truncated at `RegionName[`, so every generated id vanished and
    # the check reported clean over a set it had failed to read.
    arr = re.search(r"const\s+REGIONS[^=]*=\s*\[(.*?)\]", src, re.S)
    regions = re.findall(r"'([a-z_]+)'", arr.group(1)) if arr else []
    for m in re.finditer(r'id=\{`([A-Za-z-]+)\$\{', src):
        for r in regions:
            ids.add(m.group(1) + r.replace("_", "-"))
    return ids


def rendered() -> dict[str, str]:
    """Composition ids some prompt or workflow renders, mapped to the command that does."""
    out: dict[str, str] = {}
    files = list((REPO / "prompts").glob("*.md"))
    wf = REPO / ".github" / "workflows"
    if wf.exists():
        files += list(wf.glob("*.yml"))
    for f in files:
        for line in f.read_text(encoding="utf-8").splitlines():
            for m in re.finditer(r"remotion\s+(?:render|still)\s+([A-Za-z0-9_-]+)", line):
                out.setdefault(m.group(1), f"{f.relative_to(REPO)}: {line.strip()}")
    return out


def check() -> list[str]:
    if not ROOT_TSX.exists():
        raise FileNotFoundError(f"no Root.tsx at {ROOT_TSX}")
    reg = registered()
    ren = rendered()
    p: list[str] = []

    if not reg:
        p.append(f"parsed ZERO compositions out of {ROOT_TSX.relative_to(REPO)}. Either it "
                 f"registers none, or this checker is looking for a shape it does not use. "
                 f"Both mean the rule below is running on nothing.")
        return p

    for cid, where in sorted(ren.items()):
        if cid not in reg:
            p.append(
                f"GHOST COMPOSITION: {where} renders \"{cid}\" and Root.tsx does not register it. "
                f"Remotion exits with \"No composition with the ID '{cid}' found\", after the "
                f"research, the board, the scenes and the voice are all already done. "
                f"Registered: {', '.join(sorted(reg))}")

    for cid in sorted(reg):
        if cid in ren or cid in BY_HAND or cid.startswith(BY_HAND_PREFIX):
            continue
        p.append(f"ORPHAN COMPOSITION: Root.tsx registers \"{cid}\" and nothing renders it. "
                 f"Render it from a prompt or a workflow, or list it in BY_HAND with a reason.")

    # THE DELIVERABLE ITSELF. Named explicitly, because the whole point of this file is
    # that the film is the thing most worth being certain about.
    if "Dispatch" not in reg:
        p.append("there is no composition called \"Dispatch\". That is the film this repo exists "
                 "to make, and without it a run has no deliverable at all.")
    return p


def self_test() -> int:
    failures = 0

    def ok(label, cond, extra=""):
        nonlocal failures
        print(f"  {'ok  ' if cond else 'FAIL'}  {label}{'' if cond else '  ' + extra}")
        if not cond:
            failures += 1

    reg = registered()
    ok("compositions parse out of Root.tsx", len(reg) >= 5, str(sorted(reg)))
    ok("...including the deliverable", "Dispatch" in reg, str(sorted(reg)))
    ok("...and the generated region set", any(c.startswith("Region-") for c in reg),
       str(sorted(reg)))

    ren = rendered()
    ok("the routine's render command is found", "Dispatch" in ren, str(sorted(ren)))

    # THE FAULT THIS FILE IS FOR, on synthetic input so it cannot pass by luck.
    fake_reg = {"Proof", "CastSheet"}
    fake_ren = {"Dispatch": "prompts/x.md: npx remotion render Dispatch out/f.mp4"}
    ghosts = [c for c in fake_ren if c not in fake_reg]
    ok("an id rendered but not registered is a ghost", ghosts == ["Dispatch"], str(ghosts))

    ok("the render regex reads a real command",
       re.search(r"remotion\s+(?:render|still)\s+([A-Za-z0-9_-]+)",
                 "npx remotion render Dispatch out/dispatch/film.mp4 --props=x").group(1)
       == "Dispatch")
    ok("...and a still command too",
       re.search(r"remotion\s+(?:render|still)\s+([A-Za-z0-9_-]+)",
                 "npx remotion still FaunaSheet out/x.png --frame=14").group(1) == "FaunaSheet")
    ok("...and a hyphenated generated id",
       re.search(r"remotion\s+(?:render|still)\s+([A-Za-z0-9_-]+)",
                 "npx remotion still Region-high-plains out/x.png").group(1)
       == "Region-high-plains")

    real = check()
    ok("the repo itself is clean", not real, "\n      " + "\n      ".join(real))

    if failures:
        print(f"\ncomposition_check self-test: {failures} FAILED", file=sys.stderr)
        return 1
    print("\ncomposition_check self-test: all passed")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    if a.self_test:
        return self_test()
    try:
        problems = check()
    except (OSError, FileNotFoundError) as exc:
        print(f"composition_check: cannot run: {exc}", file=sys.stderr)
        return 2
    if problems:
        print(f"compositions: {len(problems)} problem(s)\n", file=sys.stderr)
        for x in problems:
            print(f"  - {x}", file=sys.stderr)
        return 1
    print(f"compositions: clean. {len(registered())} registered, "
          f"{len(rendered())} rendered by a prompt or a workflow.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:                                            # noqa: BLE001
        print(f"composition_check: broke: {exc}", file=sys.stderr)
        sys.exit(2)
