#!/usr/bin/env python3
"""Build the project-original Texas Dispatch signal bed from synthesis only.

No samples, model output or third-party recording enters this file. The score is intentionally
spare: low road-noise air, a four-note investigative pulse, restrained scene-change impacts and
a real dip before the causal-limit turn. It is a bed under speech, not a track competing with it.
The checked-in WAV is generated by this code so a cloud run receives identical source bytes.
"""
from __future__ import annotations

import argparse
import math
import wave
from pathlib import Path

import numpy as np

RATE = 48_000
DURATION = 48.0
SCENE_CUTS = [3.844, 11.38, 14.713, 21.033, 25.34, 29.598, 33.627, 42.0]


def smooth(points: list[tuple[float, float]], n: int) -> np.ndarray:
    xs = np.arange(n) / RATE
    t = np.array([p[0] for p in points], dtype=float)
    v = np.array([p[1] for p in points], dtype=float)
    return np.interp(xs, t, v)


def lowpass(x: np.ndarray, hz: float) -> np.ndarray:
    a = 1.0 - math.exp(-2.0 * math.pi * hz / RATE)
    y = np.empty_like(x)
    state = 0.0
    for i, value in enumerate(x):
        state += a * (float(value) - state)
        y[i] = state
    return y


def tone(t: np.ndarray, hz: float, phase: float = 0.0) -> np.ndarray:
    # A quiet fundamental plus a fast-decaying second partial reads as physical resonance rather
    # than an exposed synthesizer oscillator.
    return np.sin(2 * np.pi * hz * t + phase) + 0.18 * np.sin(4 * np.pi * hz * t + phase * 1.7)


def place(bus: np.ndarray, at: float, clip: np.ndarray, gain: float = 1.0) -> None:
    start = max(0, int(round(at * RATE)))
    end = min(len(bus), start + len(clip))
    if end > start:
        bus[start:end] += clip[:end - start] * gain


def build(duration: float = DURATION) -> np.ndarray:
    n = int(round(duration * RATE))
    t = np.arange(n) / RATE
    rng = np.random.default_rng(20260831)

    # AIR: filtered deterministic noise, breathed slowly enough to feel like room/road atmosphere.
    air = lowpass(rng.normal(0, 1, n), 720)
    air -= lowpass(air, 34)
    gust = 0.58 + 0.2 * np.sin(2 * np.pi * 0.071 * t) + 0.12 * np.sin(2 * np.pi * 0.113 * t + 1.8)
    bus = air * gust * 0.014

    # BED ARC: question -> evidence -> turn dip -> field handoff -> button -> credit resolve.
    arc = smooth([
        (0.0, 0.16), (0.6, 0.72), (6.0, 0.84), (14.7, 0.94), (21.0, 0.82),
        (24.7, 0.70), (25.25, 0.18), (26.3, 0.48), (29.6, 0.82), (34.0, 0.92),
        (39.5, 1.0), (41.6, 0.34), (42.0, 0.86), (46.5, 0.62), (48.0, 0.0),
    ], n)

    # A D/A fifth drone, with slow beating and no midrange pile-up under narration.
    drone = (tone(t, 73.416, 0.4) * 0.46 + tone(t, 110.0, 2.1) * 0.25
             + np.sin(2 * np.pi * 55.0 * t + 0.8 * np.sin(2 * np.pi * 0.09 * t)) * 0.35)
    bus += drone * arc * 0.026

    # The four-note clue motif. Notes are short, widely spaced and duck gracefully under VO.
    motif = [146.832, 174.614, 220.0, 195.998]
    pulse_times = np.arange(0.45, 41.0, 1.55)
    for i, at in enumerate(pulse_times):
        length = int(0.72 * RATE)
        tt = np.arange(length) / RATE
        env = (1 - np.exp(-tt * 38)) * np.exp(-tt * 5.8)
        shimmer = tone(tt, motif[i % len(motif)], i * 0.7) * env
        # Do not state the motif across the reveal dip. The absence prepares the snap.
        gain = 0.0 if 24.75 <= at <= 25.55 else (0.045 if i % 4 else 0.062)
        place(bus, float(at), shimmer, gain)

    # Subtle cut punctuation. A falling pitch makes the transition feel edited, not clicked.
    for i, at in enumerate(SCENE_CUTS):
        length = int((0.42 if at != 42.0 else 0.8) * RATE)
        tt = np.arange(length) / RATE
        hz = 92 - 34 * (tt / max(tt[-1], 0.001))
        phase = 2 * np.pi * np.cumsum(hz) / RATE
        env = np.sin(np.pi * np.minimum(1, tt / 0.045)) * np.exp(-tt * (8 if at != 42.0 else 4))
        hit = np.sin(phase) * env
        place(bus, at + (0.07 if i < len(SCENE_CUTS) - 1 else 0), hit,
              0.10 if at != 25.34 else 0.16)

    # The causal arrow break receives one dry two-part knock, followed by air before the answer.
    for off, hz in ((0.0, 118.0), (0.085, 73.416)):
        length = int(0.34 * RATE)
        tt = np.arange(length) / RATE
        knock = tone(tt, hz) * np.exp(-tt * 16)
        place(bus, 25.34 + off, knock, 0.11)

    # Credit tail: motif resolves downward and leaves the mark alone.
    for at, hz in ((42.2, 220.0), (43.25, 174.614), (44.35, 146.832), (45.7, 110.0)):
        length = int(1.6 * RATE)
        tt = np.arange(length) / RATE
        env = (1 - np.exp(-tt * 18)) * np.exp(-tt * 2.3)
        place(bus, at, tone(tt, hz, at) * env, 0.052)

    # Gentle fade and fixed headroom. The mixer still measures the source and sets the approved
    # voice-relative gap; this peak normalization merely makes the registry asset well formed.
    bus *= arc
    peak = float(np.max(np.abs(bus))) or 1.0
    bus *= min(1.0, 0.72 / peak)
    return np.clip(bus, -1, 1)


def write(path: Path, audio: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(path), "wb") as out:
        out.setnchannels(1)
        out.setsampwidth(2)
        out.setframerate(RATE)
        out.writeframes((audio * 32767).astype("<i2").tobytes())


def self_test() -> int:
    x = build(48.0)
    checks = [
        ("score has the declared duration", len(x) == int(48 * RATE)),
        ("score is not silent", float(np.sqrt(np.mean(x * x))) > 0.005),
        ("score keeps headroom", float(np.max(np.abs(x))) <= 0.721),
        ("turn dip is quieter than the field handoff",
         float(np.sqrt(np.mean(x[int(25.0 * RATE):int(25.25 * RATE)] ** 2)))
         < float(np.sqrt(np.mean(x[int(31.0 * RATE):int(31.25 * RATE)] ** 2)))),
        ("credits resolve instead of cutting dead",
         float(np.sqrt(np.mean(x[int(43 * RATE):int(46 * RATE)] ** 2))) > 0.002),
    ]
    for label, passed in checks:
        print(f"  {'ok  ' if passed else 'FAIL'}  {label}")
    print(f"score: {sum(not p for _, p in checks)} failure(s)")
    return 1 if any(not p for _, p in checks) else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", default="assets/music/texas_signal_bed.wav")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()
    if args.self_test:
        return self_test()
    path = Path(args.out)
    write(path, build())
    print(f"score: project-original 48 kHz bed -> {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
